[package]
name = "arrpc-process"
version = "0.1.0"
edition.workspace = true

[dependencies]
arrpc-core = { path = "../arrpc-core" }
async-trait = "0.1"
parking_lot = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

[features]
default = []
